---
    name: Build with BuildKit Cache
    run-name: ${{ github.actor }} is building the image and pushing it on DockerHub.
    on:
      push:
        branches:
          - main
      pull_request:
    
    jobs:
      build-image:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
    
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Docker build
            uses: docker/build-push-action@v4
            with:
              push: ${{ github.event_name != 'pull_request' }}
              tags: amirstm/transaction-analysis
              cache-from: type=gha
              cache-to: type=gha,mode=max